### ISSUE TITLE
Do we need to add `.aicoe-ci.yaml` in this repo?

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/build-watcher#177]
@fridex @harshad16 Do we need to add `.aicoe-ci.yaml` in this repo?

**Comment by harshad16** [comment]
@bissenbay , 
The `.aicoe-ci.yaml` is needed in all the repository which is being ported to python38.
one of the major reason being the image that is required to build the container image for the application. Another reason is for the application to have pytest based on python38.

Please kindly add the `.aicoe-ci.yaml` in the repositories, which are ported to python38 and are missing it.
you can take the reference: https://github.com/thoth-station/build-watcher/pull/176#issuecomment-733901251
If all the repos, are already added with the `.aicoe-ci.yaml` file, then thanks for all the efforts :v: 

As this repo is already added with the file, feel free to close the issue.

**Comment by bissenbay** [comment]
> @bissenbay ,
> The `.aicoe-ci.yaml` is needed in all the repository which is being ported to python38.
> one of the major reason being the image that is required to build the container image for the application. Another reason is for the application to have pytest based on python38.
> 
> Please kindly add the `.aicoe-ci.yaml` in the repositories, which are ported to python38 and are missing it.
> you can take the reference: [#176 (comment)](https://github.com/thoth-station/build-watcher/pull/176#issuecomment-733901251)
> If all the repos, are already added with the `.aicoe-ci.yaml` file, then thanks for all the efforts 
> 
> As this repo is already added with the file, feel free to close the issue.

thanks @harshad16 for the explanation

**Comment by bissenbay** [comment]
https://github.com/thoth-station/build-watcher/pull/176
